//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StripePayments.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStripe
    {
        public int id { get; set; }
        public Nullable<decimal> amnt { get; set; }
        public string cardholname { get; set; }
        public string cardno { get; set; }
        public string expDate { get; set; }
    }
}
